#!/usr/bin/env bash
# Path-parameterized driver: `run.sh <repo-path> <output-path>`.
#
# Produces a context map for <repo-path> via the OpenSpec CLI
# (https://github.com/Fission-AI/OpenSpec — npm install -g @fission-ai/openspec):
# initializes OpenSpec in the target repo if it isn't already set up there,
# then captures `openspec context`'s working-context report as the map,
# writing it to exactly <output-path>.
set -euo pipefail

[ $# -eq 2 ] || { echo "usage: run.sh <repo-path> <output-path>" >&2; exit 1; }
REPO_PATH="$1"; OUTPUT_PATH="$2"

command -v openspec >/dev/null 2>&1 || {
  echo "openspec CLI not found on PATH (npm install -g @fission-ai/openspec)" >&2
  exit 1
}

export OPENSPEC_TELEMETRY=0

if [ ! -d "$REPO_PATH/openspec" ]; then
  openspec init --tools none --force "$REPO_PATH" >&2
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# Context map for $(basename "$REPO_PATH")"
  echo
  echo "Generated by the openspec driver on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  (cd "$REPO_PATH" && openspec context)
} > "$TMP"

mv "$TMP" "$OUTPUT_PATH"
