package reposync

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/blockadence/archimedes/cli/internal/gitutil"
	"github.com/blockadence/archimedes/cli/internal/manifest"
)

// The branch, commit, and pull request the templates fan-out opens in every
// target repo. Fixed rather than configurable so a re-run updates the same
// pull request instead of opening a second one.
const (
	TemplatesBranch        = "archimedes-sync-templates"
	templatesCommitMessage = "Sync canonical PR/issue templates from Archimedes"
	templatesPRTitle       = "Sync canonical PR/issue templates"
	templatesPRBody        = "Introduces/updates this repo's .github/ pull request and issue templates from the canonical set maintained in Archimedes."
)

// ScaffoldingDirName is where an instance keeps the canonical PR and issue
// templates that get pushed into every tracked repo.
const ScaffoldingDirName = "scaffolding"

// TemplatesOptions is one templates-sync request.
type TemplatesOptions struct {
	// Root is the instance directory holding repos.yaml and scaffolding/.
	Root string
	// Repo, when set, narrows the fan-out to that one repo in repos.yaml.
	Repo string
	// DryRun reports what would change without pushing branches or opening
	// pull requests.
	DryRun bool
}

// SelectRepos returns the manifest entries the fan-out should target: every
// repo, or just the one named by filter.
func SelectRepos(m *manifest.Manifest, filter string) []manifest.Repo {
	var selected []manifest.Repo
	for _, r := range m.Repos {
		if filter != "" && r.Name != filter {
			continue
		}
		selected = append(selected, r)
	}
	return selected
}

// MultiGitterArgs builds the `multi-gitter run` invocation that applies
// scriptPath to each of slugs ("owner/name"), authenticating with token.
func MultiGitterArgs(scriptPath string, slugs []string, token string, dryRun bool) []string {
	args := []string{"run", scriptPath}
	for _, slug := range slugs {
		args = append(args, "-R", slug)
	}
	args = append(args,
		"--branch", TemplatesBranch,
		"--commit-message", templatesCommitMessage,
		"--pr-title", templatesPRTitle,
		"--pr-body", templatesPRBody,
		"--token", token,
	)
	if dryRun {
		args = append(args, "--dry-run")
	}
	return args
}

// ModScript returns the script multi-gitter runs once per cloned repo, with
// the working directory set to that clone's root. multi-gitter takes a
// single executable path and passes it no arguments, so scaffoldDir is
// baked into the script text rather than inherited through the environment
// — which keeps the script self-contained and independently runnable.
func ModScript(scaffoldDir string) string {
	return `#!/bin/sh
# Generated by ` + "`archimedes sync-templates`" + `. Run by multi-gitter with the
# working directory set to the root of each cloned repo.
set -eu
scaffolding=` + shellQuote(scaffoldDir) + `
mkdir -p .github/ISSUE_TEMPLATE
cp "$scaffolding/PULL_REQUEST_TEMPLATE.md" .github/PULL_REQUEST_TEMPLATE.md
cp "$scaffolding"/ISSUE_TEMPLATE/*.yml .github/ISSUE_TEMPLATE/
rm -f .github/ISSUE_TEMPLATE.md  # drop any legacy single-file template we're superseding
`
}

// shellQuote wraps s in single quotes, the one form no shell reinterprets,
// escaping any single quote it contains.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// SyncTemplates pushes the canonical PR/issue templates into every tracked
// repo (or the single repo named by opts.Repo) as a pull request. The
// multi-repo fan-out — cloning, branching, committing, opening the pull
// requests — is delegated to multi-gitter; the only thing owned here is
// which repos to target and what to change inside each one.
//
// progress receives multi-gitter's own output; out receives the lines meant
// for the caller.
func SyncTemplates(opts TemplatesOptions, out, progress io.Writer, run ExecFunc) error {
	root, err := filepath.Abs(opts.Root)
	if err != nil {
		return fmt.Errorf("resolving instance root %s: %w", opts.Root, err)
	}

	scaffoldDir := filepath.Join(root, ScaffoldingDirName)
	if info, err := os.Stat(scaffoldDir); err != nil || !info.IsDir() {
		return fmt.Errorf("no scaffolding directory at %s; the canonical templates live there", scaffoldDir)
	}

	manifestPath := filepath.Join(root, "repos.yaml")
	m, err := manifest.Load(manifestPath)
	if err != nil {
		return fmt.Errorf("loading %s: %w", manifestPath, err)
	}

	// The repo list comes straight from the instance's manifest — the same
	// source every other subcommand reads — so the fan-out needs no config
	// of its own. Each repo's "owner/name" slug is read off its local
	// checkout's origin remote, so the manifest never has to repeat it.
	var slugs []string
	for _, r := range SelectRepos(m, opts.Repo) {
		slug, err := gitutil.GHSlug(filepath.Join(root, r.Path))
		if err != nil {
			return fmt.Errorf("resolving %s: %w (run bootstrap first)", r.Name, err)
		}
		slugs = append(slugs, slug)
	}
	if len(slugs) == 0 {
		if opts.Repo != "" {
			return fmt.Errorf("no repos matched %q in %s", opts.Repo, manifestPath)
		}
		return fmt.Errorf("no repos listed in %s", manifestPath)
	}

	token, err := ghToken(run, progress)
	if err != nil {
		return err
	}

	scriptPath, cleanup, err := writeModScript(scaffoldDir)
	if err != nil {
		return err
	}
	defer cleanup()

	fmt.Fprintf(out, "Syncing templates from %s into %d repo(s): %s\n",
		scaffoldDir, len(slugs), strings.Join(slugs, ", "))
	if opts.DryRun {
		fmt.Fprintln(out, "Dry run: multi-gitter will report changes without pushing or opening pull requests.")
	}

	// multi-gitter's per-repo report is the result of the run, so it goes to
	// out; its logs go to progress.
	return run("multi-gitter", MultiGitterArgs(scriptPath, slugs, token, opts.DryRun), out, progress)
}

// writeModScript materializes ModScript as an executable temp file, since
// multi-gitter takes a path to run rather than a command string. The
// returned cleanup removes it.
func writeModScript(scaffoldDir string) (path string, cleanup func(), err error) {
	f, err := os.CreateTemp("", "archimedes-sync-templates-*.sh")
	if err != nil {
		return "", nil, fmt.Errorf("creating mod script: %w", err)
	}
	path = f.Name()
	cleanup = func() { os.Remove(path) }

	if _, err := io.WriteString(f, ModScript(scaffoldDir)); err != nil {
		f.Close()
		cleanup()
		return "", nil, fmt.Errorf("writing mod script: %w", err)
	}
	if err := f.Close(); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("writing mod script: %w", err)
	}
	if err := os.Chmod(path, 0o755); err != nil {
		cleanup()
		return "", nil, fmt.Errorf("making mod script executable: %w", err)
	}

	return path, cleanup, nil
}
